name: CI-CD Pipeline

on:
push:
branches:
- main

jobs:
ci:
runs-on: ubuntu-latest

steps:
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Setup Node.js
    uses: actions/setup-node@v4
    with:
      node-version: 20

  # Backend
  - name: Install backend dependencies
    run: |
      cd server
      npm install

  - name: Run backend tests
    run: |
      cd server
      npm test

  # Frontend
  - name: Install frontend dependencies
    run: |
      cd frontend
      npm install

  - name: Build frontend
    run: |
      cd frontend
      npm run build



deploy:
needs: ci  # runs only if ci runs properly
runs-on: ubuntu-latest


steps:
  - name: Deploy via SSH
    uses: appleboy/ssh-action@v1.0.3
    with:
      host: ${{ secrets.VM_HOST }}
      username: ${{ secrets.VM_USER }}
      key: ${{ secrets.VM_SSH_KEY }}
      script: |
        cd /home/rishabh/MernChatApp

        git pull origin main

        cd server
        npm install

        cd ../frontend
        npm install

        pm2 restart backend
        pm2 restart frontend

